In [2]:
import numpy as np

#create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions.

np.linspace(-1.3, 2.5, 64)

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

In [2]:
#Generate an array of length 3n, filled with the cyclic pattern 1, 2, 3. Where n is a natural number.

#n = int(input("Enter a natural number n :"))
import numpy as np

n = 3
pattern = [1,2,3]
array = np.tile(pattern, n)

print(array)


[1 2 3 1 2 3 1 2 3]


In [5]:
# Create an array of the first n odd integers, n is a natural number input from user.

import numpy as np

n = 21
odd_numbers  = np.arange(1, n, 2)
print(odd_numbers)


[ 1  3  5  7  9 11 13 15 17 19]


In [26]:
#Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

import numpy as np
arr = np.zeros([10, 10])
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1

#arr[1, :] = 1
print(arr)



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [31]:
#Create an 8 x 8 array with a checkerboard pattern of zeros and ones.

import numpy as np

arr = np.zeros([8,8], dtype=int)

arr[1::2, ::2] = 1 # odd rows, even columns
arr[::2, 1::2] = 1 #even rows, odd columns

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [34]:
#Create an array x with 100 points in the interval [-1, 1] (the points must be uniformly spaced). 
# Then create another array y where y = x ^ 2 sin(x^2) + x
# Try to plot y vs x using matplotlib.

import numpy as np
x = np.linspace(-1, 1, 100)
print(x)

y = x ** 2 * np.sin(x ** 2) + x
print(y)

[-1.         -0.97979798 -0.95959596 -0.93939394 -0.91919192 -0.8989899
 -0.87878788 -0.85858586 -0.83838384 -0.81818182 -0.7979798  -0.77777778
 -0.75757576 -0.73737374 -0.71717172 -0.6969697  -0.67676768 -0.65656566
 -0.63636364 -0.61616162 -0.5959596  -0.57575758 -0.55555556 -0.53535354
 -0.51515152 -0.49494949 -0.47474747 -0.45454545 -0.43434343 -0.41414141
 -0.39393939 -0.37373737 -0.35353535 -0.33333333 -0.31313131 -0.29292929
 -0.27272727 -0.25252525 -0.23232323 -0.21212121 -0.19191919 -0.17171717
 -0.15151515 -0.13131313 -0.11111111 -0.09090909 -0.07070707 -0.05050505
 -0.03030303 -0.01010101  0.01010101  0.03030303  0.05050505  0.07070707
  0.09090909  0.11111111  0.13131313  0.15151515  0.17171717  0.19191919
  0.21212121  0.23232323  0.25252525  0.27272727  0.29292929  0.31313131
  0.33333333  0.35353535  0.37373737  0.39393939  0.41414141  0.43434343
  0.45454545  0.47474747  0.49494949  0.51515152  0.53535354  0.55555556
  0.57575758  0.5959596   0.61616162  0.63636364  0.

In [38]:
#Create a function which creates an n*n array with (i,j) -entry equal to i + j

import numpy as np

def create_sum_array(n):
    row_indices = np.arange(n).reshape(n, 1) #this will crete a  column vector  shape(n,1)
    col_indices = np.arange(n).reshape(1, n) #this will crete a  row vector shape(1,n)

    #Broadcasting : column vector  + row vector gives (i+j) for each entry

    return row_indices + col_indices

n = 5
arr = create_sum_array(n)
print(arr)
 

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [39]:
#Evaluate cos and sin on the interval [0,1] with 1000 points and then stack the results into a tall array with rows being the 
#cos(x), sin(x))entries.

import numpy as np

x = np.linspace(0,1, 1000)

cos_x = np.cos(x)
sin_x = np.sin(x)

result = np.column_stack((cos_x, sin_x))

print(result)

[[1.         0.        ]
 [0.9999995  0.001001  ]
 [0.999998   0.002002  ]
 ...
 [0.54198585 0.84038761]
 [0.54114435 0.84092972]
 [0.54030231 0.84147098]]


In [43]:
# Create a random (3*5) array using the np.random.rand(3 ,5) function and compute: the sum of all the entries, the sum of the rows, and the sum of the columns.

import numpy as np

a = np.random.rand(3,5)

sum_all = np.sum(a)

sum_rows = np.sum(a, axis = 1)

sum_cols = np.sum(a, axis = 0)

print(a, sum_all, sum_rows, sum_cols)

[[0.06999302 0.33971926 0.97647134 0.00614203 0.35323065]
 [0.1283128  0.33565022 0.06793384 0.4741461  0.416115  ]
 [0.76171193 0.8471097  0.55643438 0.15806807 0.83248841]] 6.323526755025985 [1.7455563  1.42215797 3.15581249] [0.96001775 1.52247918 1.60083956 0.6383562  1.60183406]


In [48]:
#Create a random 5*5 array using the function np.random.rand(5, 5). Then sort the rows according to the second column.

import numpy as np

a = np.random.rand(5, 5)

print(a)

sorted_a =  a[a[:1].argsort()]

print(sorted_a)

[[0.89285061 0.26255338 0.16150027 0.80014649 0.99482136]
 [0.50099688 0.20801868 0.85152492 0.05642998 0.24674839]
 [0.90866968 0.13633879 0.52791532 0.79301519 0.54088026]
 [0.68264784 0.20523588 0.88215357 0.24773949 0.53650116]
 [0.91646464 0.33501546 0.16585237 0.66281166 0.49154698]]
[[[0.90866968 0.13633879 0.52791532 0.79301519 0.54088026]
  [0.50099688 0.20801868 0.85152492 0.05642998 0.24674839]
  [0.68264784 0.20523588 0.88215357 0.24773949 0.53650116]
  [0.89285061 0.26255338 0.16150027 0.80014649 0.99482136]
  [0.91646464 0.33501546 0.16585237 0.66281166 0.49154698]]]
